kind: Service
apiVersion: v1
metadata:
  name: pihole-service
spec:
  type: NodePort
  selector: 
    app: pihole
  ports:
    - name: dns
      nodePort: 30053
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dhcp
      nodePort: 30067
      port: 67
      targetPort: 67
      protocol: TCP
    - name: http
      nodePort: 30080
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      nodePort: 30443
      port: 443
      targetPort: 443
      protocol: TCP